import json
import logging

from google import genai
from google.genai import types

from src.ai.prompts import JSON_REPAIR_PROMPT, SYSTEM_PROMPT, USER_PROMPT_TEMPLATE
from src.config import settings

logger = logging.getLogger(__name__)


class GeminiClient:
    def __init__(self) -> None:
        self._client = genai.Client(api_key=settings.GEMINI_API_KEY)

    async def extract_rules(
        self,
        text_chunk: str,
        document_name: str,
        chunk_index: int,
        total_chunks: int,
    ) -> list[dict]:
        """Send a single text chunk to Gemini and return a list of parsed rule dicts."""
        user_content = USER_PROMPT_TEMPLATE.format(
            document_name=document_name,
            chunk_index=chunk_index,
            total_chunks=total_chunks,
            text_chunk=text_chunk,
        )
        response = await self._client.aio.models.generate_content(
            model=settings.GEMINI_MODEL,
            contents=user_content,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                max_output_tokens=4096,
                temperature=0.2,
            ),
        )
        raw = response.text.strip() if response.text else ""

        # Strip markdown fencing
        if raw.startswith("```"):
            raw = raw.split("```", 2)[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.rsplit("```", 1)[0].strip()

        # Try to load JSON exactly as generated by the model.
        # If it contains unescaped backslashes, `json.loads` will fail,
        # and the JSON_REPAIR_PROMPT will handle fixing it.

        try:
            result = json.loads(raw)
            if not isinstance(result, list):
                logger.warning("Gemini returned non-list JSON, wrapping in list")
                result = [result] if isinstance(result, dict) else []
            return result
        except json.JSONDecodeError as e:
            logger.warning("JSON parse failed for chunk %d/%d, attempting repair: %s", chunk_index, total_chunks, e)
            return await self._repair_json(raw, str(e))

    async def _repair_json(self, broken: str, error: str) -> list[dict]:
        """Follow-up call asking Gemini to fix its own malformed JSON output."""
        response = await self._client.aio.models.generate_content(
            model=settings.GEMINI_MODEL,
            contents=JSON_REPAIR_PROMPT.format(error=error, broken=broken),
            config=types.GenerateContentConfig(
                system_instruction="You are a JSON repair assistant. Return ONLY valid JSON, nothing else.",
                max_output_tokens=4096,
                temperature=0.0,
            ),
        )
        raw = response.text.strip()

        # Strip markdown fencing
        if raw.startswith("```"):
            raw = raw.split("```", 2)[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.rsplit("```", 1)[0].strip()

        try:
            result = json.loads(raw)
            return result if isinstance(result, list) else []
        except json.JSONDecodeError:
            logger.error("JSON repair also failed, returning empty list")
            return []
